.TH GIP 1 "October 21, 2004"
.SH NAME
gip \- IP calculator for GNOME desktop environment.
.SH SYNOPSIS
.B gip
.SH DESCRIPTION
.PP
\fBgip\fP provides system administrators with tools for IP address based calculations. For example, an administrator who needs to find out which IP prefix length equals the IP netmask 255.255.240.0, just types in the mask and gets the prefix length presented. But many more advanced calculations can be made. Gip can convert an address range into a list of prefix lengths. It can also split subnets using a given IP netmask or IP prefix length. Many more calculations are possible.
.SH OPTIONS
There are no options.
.SH SEE ALSO
.BR gipsc (1),
.BR ipsc (1),
.BR prips (1).
.br
.SH AUTHOR
gip was written by Samuel Abels <spam@debain.org>.
.PP
This manual page was written by Khalid El Fathi <invent@edena-fr.org>,
for the Debian project (but may be used by others).
